version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./database-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME:"root"
      - MONGO_INITDB_ROOT_PASSWORD:"root"
      - MONGO_INITDB_DATABASE:"patients"

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME:"root"
      - ME_CONFIG_MONGODB_ADMINPASSWORD:"root"
      - ME_CONFIG_MONGODB_SERVER=mongodb